[[language]]
name = "c"
indent = { tab-width = 8, unit = "\t" }

[[language]]
name = "cpp"
indent = { tab-width = 8, unit = "\t" }

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "javascript"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "js" ] }
auto-format = true

[[language]]
name = "json"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "json" ] }

[[language]]
name = "markdown"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "md" ] }
# auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "ts" ] }
auto-format = true

[[language]]
name = "jsx"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "jsx" ] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "tsx" ] }
auto-format = true

[language-server.rust-analyzer.config]
diagnostics.disabled = [ "inactive-code" ]

[[language]]
name = "python"
language-servers = [ "ruff-lsp" ]
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

